### ISSUE TITLE
Comment pagination does not work in the official K2 release if page caching is enabled

### ISSUE THREAD

**Issue by cmirnow** [eworkers/K2ForJ4#10]
**Warning, this is not a K2ForJ4 problem! This problem is inherent in the official K2 release.** Perhaps it can be solved now?

If standard caching + cache plugin is enabled, K2 comment pagination does not work. The cache won't let you go to another page. You can do this test [here](https://masterpro.ws/jweather-by-ip-pogoda-po-ip-dlya-joomla).

~~By the way, for me this is another argument that K2ForJ4 caching isn't working correctly at the moment (this problem isn't there now).~~

**Comment by eworkers** [comment]
Regarding this issue, we delayed the reply as were busy in tackling issues as you can see.
The thing with this issue that comments are stitched to K2 item view by design, hence they are part of the K2 item page display!
This is design mater of K2 itself. In order to overcome this problem, a different approach should be introduced of how K2 comment should be handled within an item (a complete refactor for comment handling in K2 item). We cannot think of one at the moment that will not introduce legacy compatibility issue for users, and since this fork should be only a transient toward K2 official new version such a refactor should not take place. 
Maybe this can be addressed in the new fork we were planning to have, but not in this version.

Unless you are not convinced or you have an idea about how to overcome this without breaking things for existing users, please close this issue as it is matter of K2 design, otherwise please share your argument or idea(s) in here again.

**Comment by cmirnow** [comment]
OK. TODO. Closed.
