### ISSUE TITLE
Comments do not work properly

### ISSUE THREAD

**Issue by cmirnow** [eworkers/K2ForJ4#35]
Joomla 3.10.11, php 8.0 {
1. After upgrading from K2 to K2ForJ4 it is impossible to leave a comment without authorization.

2. If I logged into the site as an admin, the comment appears on the site without moderation (contrary to the settings, Enable comment auto-publishing - No).

Information message doesn't appear in both cases.
}

3. Joomla 4. Comments work. But the comment of the admin appears on the site without moderation (maybe I'm wrong? the option "Enable comment auto-publishing" should be executed for the superuser too).

**Comment by eworkers** [comment]
> Joomla 3.10.11, php 8.0 {
> 
> 1. After upgrading from K2 to K2ForJ4 it is impossible to leave a comment without authorization.
> 2. If I logged into the site as an admin, the comment appears on the site without moderation (contrary to the settings, Enable comment auto-publishing - No).
> 
> Information message doesn't appear in both cases. }
> 
> 3. Joomla 4. Comments work. But the comment of the admin appears on the site without moderation (maybe I'm wrong? the option "Enable comment auto-publishing" should be executed for the superuser too).

Hello again @cmirnow, Sorry for delaying this replay so long, but we were busy re-allocating our company, plus we took things slowly since K2 official team announced that their official version will be ready in January

As for the issue: 1&2 unfortunately we are unable to reproduce
![k2comment](https://user-images.githubusercontent.com/115772544/214772341-f26dfcf4-0284-43c0-8910-d0dfe172a577.png)
As you can see from the screenshot, both work as expected. maybe you can help us more to reproduce

As for 3, correct me if I'm wrong, but isn't this how K2 official version behave? Plus it makes sense, since admin can moderate comments and is able to perform all the CRUD operation
