### ISSUE TITLE
Attachments Ordering PR

### ISSUE THREAD

**Issue by martyharty** [eworkers/K2ForJ4#69]
I got this https://github.com/getk2/k2/pull/511/commits working with two changes:

administrator/components/com_k2/models/item.php
$attOrderings = Factory::getApplication()->input->post->get('attachmentordering', [], 'array');

administrator/components/com_k2/helpers/html.php
$document->addScript('https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js');
//$document->addScript('https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.8.24/jquery-ui.min.js');

Trying a new PR myself got a bit messy, but I like the feature

**Comment by eworkers** [comment]
Please note that this repo is supposed to be compatible with K2 official future compatible version with J>=4
We promised users not to violate this rule, this is not an issue, it is a feature request that currently is not available within K2 official version.

Adding it will break future compatibility with K2 official version if they offered a J>=4 compatible release.
In case K2 officially supported, we will support it in no time.
At the moment we will shift our effort toward K2ForJ4 Joomla 6 compatibility 

In case we decided to provide a complete fork with a different name, we would be glad to add this feature and many other features that we think K2 is still missing. But such a decision is not made yet because JoomlaWorks has recently promised that K2 J4 and J5 compatible version is nearby.
