### ISSUE TITLE
Caching doesn't work for K2ForJ4?

### ISSUE THREAD

**Issue by cmirnow** [eworkers/K2ForJ4#9]
I don't see any K2 cache files (Joomla 4, php 8.1, website with K2 content has been upgraded from Joomla 3 to Joomla 4) : 

`administrator/index.php?option=com_cache`

Also, by some indications, K2 content is not cached now. Please close this issue if I am wrong.

**Comment by eworkers** [comment]
Hello @cmirnow 
Let us first mention that you are our favorite committer! we are witnessing a huge number of clones and visits on this repo yet you are the only one caring enough to share your experience for this fork. So thank you for that, you are helping everyone who need this (temp) transition.

regarding the issue, I think what you are seeing when you visit (administrator/index.php?option=com_cache) Joomla cache component is the total number of cached pages. So in order to test if K2 pages were cached or not, try watch the counter and visit a K2 page that haven't visited before then refresh (administrator/index.php?option=com_cache), if you witnessed that the total number of pages increased then everything is working as expected, we already tested but will not close until you test. If all things went well for you, please close this issue yourself

**Comment by cmirnow** [comment]
Thank you @eworkers , you're doing a great job and I'm happy to help. But the problem remains. I see a difference in the caching performance of the official K2 version and your fork. Take a look, this is the state of the cache after visiting many K2 articles. (!) Among other things, there is another criterion, which I will tell you about in the next commit...

![k2_cache](https://user-images.githubusercontent.com/10660173/203427863-095d60c5-4a70-467b-9866-372a772dc5e9.jpg)

**Comment by cmirnow** [comment]
By comparison. K2 v.2.10.3

![k2_cache_j3](https://user-images.githubusercontent.com/10660173/203432715-75fb8f83-db3b-475b-ade5-8f76f2f6fc2e.jpg)
